### Signin Request
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "atri0048@student.monash.edu",
  "password": "1234567890"
}

### Signup Request
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "studentId": 35096985,
  "monashEmail": "atri0048@student.monash.edu",
  "password": "1234567890",
  "firstName": "Aditya",
  "lastName": "Tripathi",
  "yearOfStudy": 3
}

### Forgot Password Request
PATCH http://localhost:3000/auth/forgot-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNTA5Njk4NSwibW9uYXNoX2VtYWlsIjoiYXRyaTAwNDhAc3R1ZGVudC5tb25hc2guZWR1IiwidXNlcm5hbWUiOiJhdHJpMDA0OCIsInBhc3N3b3JkX2hhc2giOiIkYXJnb24yaWQkdj0xOSRtPTY1NTM2LHQ9MyxwPTQkb0k4R3g5VloybTBSdTJtNlZPTGQ0ZyRKb1IybmtzS3hpTndteDhXZ0dWbVQ1NCtWbUVNVkF1RVdvQVBBTHV1SnIwIiwiZmlyc3RfbmFtZSI6IkFkaXR5YSIsImxhc3RfbmFtZSI6IlRyaXBhdGhpIiwicHJvZmlsZV9waWN0dXJlX3VybCI6bnVsbCwiYmlvIjpudWxsLCJrYXJtYV9wb2ludHMiOjAsInllYXJfb2Zfc3R1ZHkiOjMsImlzX3ZlcmlmaWVkX3N0dWRlbnQiOmZhbHNlLCJjcmVhdGVkX2F0IjoiMjAyNS0wNS0wOVQxMDoxMzozNy4yMTdaIiwidXBkYXRlZF9hdCI6IjIwMjUtMDUtMDlUMTA6MTM6MzcuMjE3WiIsImNhbXB1c19pZCI6bnVsbCwiZmFjdWx0eV9pZCI6bnVsbCwiY291cnNlX2lkIjpudWxsLCJpYXQiOjE3NDY3ODU2MjAsImV4cCI6MTc0Njc4OTIyMH0.X7hjlH53zVVS3YjtyZ2935Hxqsu_b7GUFnnzNSZXxy8

{
  "email": "atri0048@student.monash.edu",
  "newPassword": "1234567890"
}

### Delete Request
DELETE http://localhost:3000/auth/delete-account
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNTA5Njk4NSwibW9uYXNoX2VtYWlsIjoiYXRyaTAwNDhAc3R1ZGVudC5tb25hc2guZWR1IiwidXNlcm5hbWUiOiJhdHJpMDA0OCIsInBhc3N3b3JkX2hhc2giOiIkYXJnb24yaWQkdj0xOSRtPTY1NTM2LHQ9MyxwPTQkb0k4R3g5VloybTBSdTJtNlZPTGQ0ZyRKb1IybmtzS3hpTndteDhXZ0dWbVQ1NCtWbUVNVkF1RVdvQVBBTHV1SnIwIiwiZmlyc3RfbmFtZSI6IkFkaXR5YSIsImxhc3RfbmFtZSI6IlRyaXBhdGhpIiwicHJvZmlsZV9waWN0dXJlX3VybCI6bnVsbCwiYmlvIjpudWxsLCJrYXJtYV9wb2ludHMiOjAsInllYXJfb2Zfc3R1ZHkiOjMsImlzX3ZlcmlmaWVkX3N0dWRlbnQiOmZhbHNlLCJjcmVhdGVkX2F0IjoiMjAyNS0wNS0wOVQxMDoxMzozNy4yMTdaIiwidXBkYXRlZF9hdCI6IjIwMjUtMDUtMDlUMTA6MTM6MzcuMjE3WiIsImNhbXB1c19pZCI6bnVsbCwiZmFjdWx0eV9pZCI6bnVsbCwiY291cnNlX2lkIjpudWxsLCJpYXQiOjE3NDY3ODU2MjAsImV4cCI6MTc0Njc4OTIyMH0.X7hjlH53zVVS3YjtyZ2935Hxqsu_b7GUFnnzNSZXxy8

{}