### Signin Request
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "atri0048@student.monash.edu",
  "password": "123456789"
}

### Signup Request
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "studentId": 35096985,
  "monashEmail": "atri0048@student.monash.edu",
  "password": "1234567890",
  "firstName": "Aditya",
  "lastName": "Tripathi",
  "yearOfStudy": 3
}

### Delete User
DELETE http://localhost:3000/user/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjM1MDk2OTg1LCJlbWFpbCI6ImF0cmkwMDQ4QHN0dWRlbnQubW9uYXNoLmVkdSIsImlhdCI6MTc0NzAxNjI4OX0.WgR-pQK-zLIRogakwB2O2t3JbEeg0LRbXp3hs-7yzYQ

### Get current user
GET http://localhost:3000/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjM1MDk2OTg1LCJlbWFpbCI6ImF0cmkwMDQ4QHN0dWRlbnQubW9uYXNoLmVkdSIsImlhdCI6MTc0NzAxNjI4OX0.WgR-pQK-zLIRogakwB2O2t3JbEeg0LRbXp3hs-7yzYQ

### Forgot Password
PATCH http://localhost:3000/user/forgot-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjM1MDk2OTg1LCJlbWFpbCI6ImF0cmkwMDQ4QHN0dWRlbnQubW9uYXNoLmVkdSIsImlhdCI6MTc0NzAxNjI4OX0.WgR-pQK-zLIRogakwB2O2t3JbEeg0LRbXp3hs-7yzYQ
Content-Type: application/json

{
  "password": "1234567890"
}