export * from "./course";
export * from "./event";
export * from "./eventType";
export * from "./freeSlots";
export * from "./interest";
export * from "./studentType";
export * from "./tag";
export * from "./unit";
export * from "./user";
